<style>
  /* MÉTRICAS e CARTÕES customizados */
  .metric-container {
    background: #F9F9FF;
    border: 1px solid #E0E0E0;
    border-radius: 8px;
    box-shadow: 0 2px 4px rgba(0,0,0,0.1);
    padding: 1rem;
  }
  /* SLIDERS, SELECTBOX, RADIOBUTTONS */
  .stSlider > div[data-baseweb="slider"] { 
    border-radius: 8px !important;
  }
  .stSelectbox [role="listbox"],
  .stRadio [role="radiogroup"] {
    border: 1px solid #E0E0E0;
    border-radius: 8px;
    padding: 0.5rem;
  }
  /* TÍTULOS (h1,h2) */
  h1 { font-size: 32px; font-weight: 700; font-family: "Times New Roman", serif; }
  h2 { font-size: 24px; font-weight: 600; font-family: "Times New Roman", serif; }

  /* BOTOÕES */
  .stButton>button {
    border-radius: 12px;
    background-color: #2F5496;
    color: white;
  }
  .stButton>button:hover {
    background-color: #244B78;
  }

  /* REMOÇÃO DE CSS GLOBAL PROBLEMÁTICO */
  /* comentei .stContainer para não quebrar seus col_map/col_charts */
  /* .stContainer { padding: 1rem 2rem !important; } */
</style>
